Document: hgd
Title: Debian hgd Manual
Author: <insert document author here>
Abstract: This manual describes what hgd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hgd/hgd.sgml.gz

Format: postscript
Files: /usr/share/doc/hgd/hgd.ps.gz

Format: text
Files: /usr/share/doc/hgd/hgd.text.gz

Format: HTML
Index: /usr/share/doc/hgd/html/index.html
Files: /usr/share/doc/hgd/html/*.html
